#!/bin/bash


sudo /sbin/iw phy phy0 interface add uap0 type __ap

echo "step 1 completed"

sleep 2

    sudo sh -c 'echo "interface=lo,uap0
no-dhcp-interface=lo,wlan0
bind-interfaces
server=8.8.8.8
dhcp-range=10.10.50.50,10.10.50.255,12h" > /etc/dnsmasq.conf'


echo "step 2"

	echo "interface=uap0
ssid=$1
hw_mode=g
channel=6
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=$2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP" | sudo tee /etc/hostapd/hostapd.conf


echo step 3

#sudo sed -i "s/\(ssid *= *\).*/\1$ ssid\"$1\"/" /etc/hostapd/hostapd.conf
#sudo sed -i "s/\(wpa_passphrase *= *\).*/\1$wpa_passphrase\"$2\"/" /etc/hostapd/hostapd.conf


	sudo sh -c 'echo "DAEMON_CONF=\"/etc/hostapd/hostapd.conf\"" > /etc/default/hostapd'

echo "step 4"

sudo systemctl restart dnsmasq

sleep 2

echo "step 5"

sudo systemctl restart hostapd

sudo ifdown wlan0
sudo ifup wlan0

sudo sed -i '/exit 0/d' /etc/rc.local

echo "
sleep 5
sudo ifdown wlan0
sleep 2
sudo rm -f /var/run/wpa_supplicant/wlan0
sudo ifup wlan0
exit 0" |  sudo tee -a  /etc/rc.local
